'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class AgendaTarefaEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=AgendaTarefaEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Prioridades() As DbSet(Of Prioridade)
    Public Overridable Property Status() As DbSet(Of Status)
    Public Overridable Property Tarefas() As DbSet(Of Tarefa)
    Public Overridable Property TipoTarefas() As DbSet(Of TipoTarefa)
    Public Overridable Property Usuarios() As DbSet(Of Usuario)

End Class
