'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TipoTarefa
    Public Property Id As Integer
    Public Property Nome As String
    Public Property Cor As String
    Public Property Usuario As Integer

    Public Overridable Property Tarefas As ICollection(Of Tarefa) = New HashSet(Of Tarefa)
    Public Overridable Property Usuario1 As Usuario

End Class
